/**
 * Classification only. A writer is implemented here only for finished-goods receive,
 * where the model, mutation capability, tenant rule, and business-event contract
 * already exist. Missing pieces stay named. No capability string is invented.
 */

export const LIVE_WRITER_MATRIX = [
  {
    domain: 'purchase_request_transition',
    model: 'OsPurchaseRequest + status history',
    capability: 'purchasing.operational.record',
    tenantPredicate: 'authorizePurchaseRequestTransition',
    audit: 'in-memory event object; no canonical Prisma/outbox writer',
    state: 'NOT_IMPLEMENTED',
    blocker: 'FOUNDATION_GAP',
    detail: 'The transition command exists in memory. A Prisma writer and outbox persistence contract are not both already canonical.',
  },
  {
    domain: 'production_entry',
    model: 'OsProductionTraceEntry',
    capability: 'production.entry.member',
    tenantPredicate: 'session organization on the in-memory store',
    audit: 'append-only trace; no canonical outbox writer',
    state: 'NOT_IMPLEMENTED',
    blocker: 'FOUNDATION_GAP',
    detail: 'production.review.member does not authorize entry. The live writer is still the in-memory trace store.',
  },
  {
    domain: 'quema_start_end',
    model: 'OsProductionQuema + OsProductionQuemaTime',
    capability: 'production.entry.member',
    tenantPredicate: 'session organization on the in-memory store',
    audit: 'in-memory quema facts; no canonical outbox writer',
    state: 'NOT_IMPLEMENTED',
    blocker: 'FOUNDATION_GAP',
    detail: 'Quema remains multi-product. Start and end are not a Prisma command yet.',
  },
  {
    domain: 'loss',
    model: 'OsProductionTraceEntry kind loss',
    capability: 'production.entry.member',
    tenantPredicate: 'session organization on the in-memory store',
    audit: 'append-only trace; no canonical outbox writer',
    state: 'NOT_IMPLEMENTED',
    blocker: 'FOUNDATION_GAP',
    detail: 'Loss facts already have a contract. The persistent command writer is not canonical.',
  },
  {
    domain: 'consumption',
    model: 'OsProductionTraceEntry kind consumption',
    capability: 'production.entry.member',
    tenantPredicate: 'session organization on the in-memory store',
    audit: 'append-only trace; no stock decrement; no canonical outbox writer',
    state: 'NOT_IMPLEMENTED',
    blocker: 'FOUNDATION_GAP',
    detail: 'Reported consumption does not decrement authoritative stock. No Prisma writer is added.',
  },
  {
    domain: 'finished_goods_receive',
    model: 'OsFinishedGoodsReceipt',
    capability: 'warehouse.finished_goods.receive',
    tenantPredicate: 'session organization; citations proven in that organization',
    audit: 'os_business_events finished_goods.received / finished_goods.corrected',
    state: 'IMPLEMENTED',
    blocker: null,
    detail: 'Additive migration exists and is not applied. Receive does not allocate and does not post stock.',
  },
  {
    domain: 'allocation',
    model: 'OsOrderAllocation',
    capability: 'warehouse.finished_goods.allocate',
    tenantPredicate: 'AllocationTenantTargets keyed by session organization',
    audit: 'in-memory insert; live write marked UNPROVEN',
    state: 'NOT_IMPLEMENTED',
    blocker: 'FOUNDATION_GAP',
    detail: 'Allocation remains a later warehouse operation. The existing command is not a database writer.',
  },
  {
    domain: 'warehouse_exit',
    model: 'warehouse exit persistence used by the fulfillment reader',
    capability: 'not a receive or allocate scope',
    tenantPredicate: 'fulfillment read is tenant-scoped; write command is not canonical here',
    audit: 'no confirmed outbox writer in this pass',
    state: 'NOT_IMPLEMENTED',
    blocker: 'FOUNDATION_GAP',
    detail: 'Warehouse exit is not delivery. No new writer is added.',
  },
  {
    domain: 'delivery',
    model: 'delivery persistence used by the fulfillment reader',
    capability: 'delivery.record',
    tenantPredicate: 'not proven as a write command in this pass',
    audit: 'no confirmed outbox writer in this pass',
    state: 'NOT_IMPLEMENTED',
    blocker: 'FOUNDATION_GAP',
    detail: 'delivery.record does not imply allocate. Nota de Entrega is not invented.',
  },
  {
    domain: 'customer_communication',
    model: 'OsCustomerConversation is evidence, not an informed-status column',
    capability: 'no canonical informed-of-order write located',
    tenantPredicate: 'conversation rows are tenant-scoped',
    audit: 'conversation is not the informed fact',
    state: 'NOT_IMPLEMENTED',
    blocker: 'FOUNDATION_GAP',
    detail: 'A message is not customer-informed. CustomerDateInformedRecord covers date-issue notice only.',
  },
  {
    domain: 'coordination_decision',
    model: 'OsCoordinationDecision',
    capability: 'coordination.decision.record',
    tenantPredicate: 'existing decision command is organization-scoped',
    audit: 'decision row is the record; record is not a read capability',
    state: 'NOT_IMPLEMENTED',
    blocker: 'CROSS_LANE_CHANGE_REQUEST',
    detail: 'The write command already exists. This pass does not add a second writer and does not use the record scope as a read.',
  },
  {
    domain: 'commercial_exception_authorization',
    model: 'no dedicated commercial-exception persistence confirmed as the write target',
    capability: 'commercial.exception.authorize',
    tenantPredicate: 'explicit capability only; title grants nothing',
    audit: 'not confirmed as an outbox contract',
    state: 'NOT_IMPLEMENTED',
    blocker: 'FOUNDATION_GAP',
    detail: 'The capability exists. A Prisma writer is not added without a confirmed model and audit contract.',
  },
  {
    domain: 'special_order_classification',
    model: 'OsSpecialOrderClassification',
    capability: 'no dedicated write capability confirmed',
    tenantPredicate: 'classification rows are organization-scoped',
    audit: 'not confirmed as an outbox contract',
    state: 'NOT_IMPLEMENTED',
    blocker: 'CROSS_LANE_CHANGE_REQUEST',
    detail: 'Pedido Especial stays an explicit classification. No numeric threshold and no invented write scope.',
  },
] as const;

export const CUSTOMER_INFORMED_FOUNDATION_GAP = {
  kind: 'FOUNDATION_GAP' as const,
  id: 'CUSTOMER_INFORMED_OF_ORDER',
  missingFact:
    'An explicit record that the customer was informed about an operating fact other than a ProductionDateIssue, with occurredAt, actor/source, and the related order or customer. CustomerDateInformedRecord covers date-issue notice only. OsCustomerConversation is not that fact.',
} as const;

export const COORDINATION_READ_AUTHORITY = {
  kind: 'CROSS_LANE_CHANGE_REQUEST' as const,
  id: 'COORDINATION_READ_AUTHORITY',
  doNotUse: ['coordination.decision.record', 'operations.coordinator.record'] as const,
  detail:
    'OsCoordinationDecision is persisted. No canonical read capability exists. The reader stays behind a closed gate.',
} as const;
