/** OS foundation event types — canonical BusinessEvent registry (Step 10+). */
export const OS_FOUNDATION_EVENT_TYPES = [
  'member.invited',
  'member.activated',
  'member.department.changed',
  'member.role.changed',
  'member.manager.changed',
  'member.suspended',
  'member.terminated',
  'employment.restarted',
  'member.email.change_requested',
  'member.email.changed',
  'delegation.granted',
  'delegation.revoked',
  'delegation.expired',
  'task.reassigned',
  'party.created',
  'party.updated',
  'party.deactivated',
  'party.reactivated',
  'party.role.assigned',
  'party.role.ended',
  'contact.updated',
  'party.fiscal_identity.changed',
  'party.duplicate.suggested',
  'party.merge.requested',
  'party.merged',
  'party.merge.rejected',
  'lead.created',
  'lead.resolved',
  'location.created',
  'location.updated',
  'location.deactivated',
  'work.created',
  'work.completed',
  'work.cancelled',
  'approval.requested',
  'approval.approved',
  'approval.rejected',
  'opportunity.created',
  'opportunity.updated',
  'opportunity.stage_changed',
  'opportunity.closed',
  'opportunity.owner_assigned',
  'quote.created',
  'quote.updated',
  'quote.line_added',
  'quote.line_updated',
  'quote.line_removed',
  'quote.submitted',
  'quote.cancelled',
  'order.created',
  'order.cancelled',
  'commercial_account.owner_reassigned',
] as const;

export type OsFoundationEventType = (typeof OS_FOUNDATION_EVENT_TYPES)[number];

export function isOsFoundationEventType(value: string): value is OsFoundationEventType {
  return (OS_FOUNDATION_EVENT_TYPES as readonly string[]).includes(value);
}
