/** Proposed admin scopes — display labels configurable per org (RD-01). */
export const ADMIN_SCOPE_KEYS = [
  'people.admin',
  'master_data.admin',
  'fiscal.admin',
  'org.admin',
  'integration.admin',
] as const;

export type AdminScopeKey = (typeof ADMIN_SCOPE_KEYS)[number];

/** Command → required scope (minimum). */
export const COMMAND_REQUIRED_SCOPES: Record<string, AdminScopeKey | 'member_active'> = {
  InviteMember: 'people.admin',
  ActivateMember: 'member_active',
  ChangeMemberEmail: 'member_active',
  RequestMemberEmailChange: 'member_active',
  ChangeDepartment: 'people.admin',
  ChangeRole: 'people.admin',
  ChangeManager: 'people.admin',
  GrantDelegation: 'people.admin',
  RevokeDelegation: 'people.admin',
  SuspendMember: 'people.admin',
  TerminateMember: 'people.admin',
  RehireMember: 'people.admin',
  RetryAuthProviderSync: 'people.admin',
  CreateWorkItem: 'member_active',
  ReassignWork: 'people.admin',
  CompleteWork: 'member_active',
  CancelWorkItem: 'member_active',
  RequestApproval: 'member_active',
  Approve: 'member_active',
  Reject: 'member_active',
  CreateParty: 'master_data.admin',
  UpdateParty: 'master_data.admin',
  DeactivateParty: 'master_data.admin',
  ReactivateParty: 'master_data.admin',
  AssignPartyRole: 'master_data.admin',
  EndPartyRole: 'master_data.admin',
  UpdateContact: 'master_data.admin',
  UpdateFiscalIdentity: 'fiscal.admin',
  CreateLead: 'master_data.admin',
  ResolveLead: 'master_data.admin',
  RequestPartyMerge: 'master_data.admin',
  ApprovePartyMerge: 'org.admin',
  RejectPartyMerge: 'org.admin',
  RetryDeadLetterDelivery: 'people.admin',
  CreateOpportunity: 'member_active',
  UpdateOpportunity: 'member_active',
  ChangeOpportunityStage: 'member_active',
  CloseOpportunity: 'member_active',
  AssignOpportunityOwner: 'member_active',
  CreateQuote: 'member_active',
  AddQuoteLine: 'member_active',
  UpdateQuoteLine: 'member_active',
  RemoveQuoteLine: 'member_active',
  UpdateQuote: 'member_active',
  SubmitQuote: 'member_active',
  CancelQuote: 'member_active',
  CreateOrder: 'member_active',
  CancelOrder: 'member_active',
};
