/**
 * Consulting Intelligence Agent — the Executive Daily Brief (Mission 20 —
 * Executive Daily Brief pass).
 *
 * Álvaro should never have to click to answer three questions: where are we
 * today, what changed since I last looked, what should I do next. This
 * module composes the same reports every primary workspace surface already
 * holds — it invents nothing:
 *
 *   - `businessUnderstanding` (the workspace's own published number) for
 *     "where are we";
 *   - the Consulting Intelligence Agent's own `NextStepVoice`
 *     (`next-step-voice.ts`) plus the Missing Information Engine's ranked
 *     opportunities for "what should I do next" (up to three, never padded
 *     when fewer than three genuinely rank);
 *   - real `workspace.timeline` / `workspace.meetings` /
 *     `workspace.knowledge.assets` timestamps, compared against a
 *     browser-local "last visit" pointer (`hooks/use-last-visit.ts` — a
 *     presentation-only convenience with no opinion Discovery, Readiness,
 *     the Capability Twin, Memory or the Consulting Intelligence cycle
 *     could possibly hold, since none of them have a concept of "a visit")
 *     for "what changed since my last visit" — an honest empty state when
 *     nothing real changed, never an invented delta;
 *   - the Discovery Complete/Incomplete ceremony's own
 *     `missingCapabilities` / `notTrackedCapabilities` (`discovery-status.ts`)
 *     for the open "next milestones".
 *
 * Every Spanish sentence here is generated in this file, same rule as the
 * rest of `lib/readiness` / `lib/consulting-intelligence` (see
 * `next-step-voice.ts`) — never routed through `lib/i18n`.
 */

import type { CompanyWorkspace, DiscoveryDimension, TimelineEvent } from "@/types";
import type { CapabilityId } from "@/lib/discovery-agent/capabilities";
import type { MissingInformationReport } from "@/lib/readiness";
import { sortTimelineNewestFirst } from "@/lib/timeline";
import type { DiscoveryCompletionStatus } from "./discovery-status";
import type { NextStepActionKind, NextStepVoice } from "./next-step-voice";

/** Browser-local "what did the workspace look like last time I opened it" pointer. Never sent to, or read by, any engine. */
export interface LastVisitSnapshot {
  visitedAt: string;
  businessUnderstanding: number;
}

export interface DailyBriefAction {
  id: string;
  /** Client-facing sentence, already generated by `NextStepVoice` or the Missing Information Engine — never rephrased here. */
  message: string;
  actionLabel: string;
  actionKind: NextStepActionKind;
  focusDimension: DiscoveryDimension | null;
  /** Only set when an existing engine already computed a concrete figure (minutes remaining, estimated lift %) — never invented. */
  impactLabel: string | null;
}

export interface DailyBriefChange {
  id: string;
  label: string;
}

export interface DailyBriefSinceLastVisit {
  /** False on the very first brief this browser has ever rendered for this workspace — there is nothing to compare against yet. */
  hasPriorVisit: boolean;
  hasChanges: boolean;
  changes: DailyBriefChange[];
  /** The one sentence the hero shows — honest empty state when `hasChanges` is false. */
  summary: string;
}

export type DailyBriefMilestoneState = "open" | "not_tracked";

export interface DailyBriefMilestone {
  id: CapabilityId;
  label: string;
  state: DailyBriefMilestoneState;
  detail: string | null;
}

export interface DailyBriefTimelineGroup {
  id: "today" | "yesterday" | "last_week" | "earlier";
  label: string;
  events: TimelineEvent[];
}

export interface ExecutiveDailyBrief {
  generatedAt: string;
  /** "Hoy Architect entiende aproximadamente el X% de cómo opera {company}." — the honest headline, never a growth claim. */
  headline: string;
  understandingPercent: number;
  sinceLastVisit: DailyBriefSinceLastVisit;
  /** Ranked, highest priority first — up to three, never padded. */
  actions: DailyBriefAction[];
  milestones: DailyBriefMilestone[];
}

export interface ExecutiveDailyBriefInput {
  workspace: CompanyWorkspace;
  nextStepVoice: NextStepVoice;
  missingInformation: MissingInformationReport;
  discoveryCompletion: DiscoveryCompletionStatus;
  /** `null` when this browser has never recorded a visit to this workspace before. */
  lastVisit: LastVisitSnapshot | null;
}

const MAX_ACTIONS = 3;
const MAX_TIMELINE_EVENTS = 12;
const DAY_MS = 24 * 60 * 60 * 1000;

function pluralEs(count: number, singular: string, plural: string): string {
  return count === 1 ? singular : plural;
}

function clampPercent(value: number): number {
  return Math.max(0, Math.min(100, Math.round(value)));
}

function buildHeadline(companyName: string, pct: number): string {
  return `Hoy Architect entiende aproximadamente el ${pct}% de cómo opera ${companyName}.`;
}

/**
 * "Desde tu última visita" — every count below is a real timestamp
 * comparison against `workspace.timeline` / `workspace.meetings` /
 * `workspace.knowledge.assets`, the same records every other surface in the
 * app already reads. No invented event, no guessed delta: when nothing
 * genuinely changed, `hasChanges` is false and the summary says so plainly.
 */
export function buildSinceLastVisit(
  workspace: CompanyWorkspace,
  lastVisit: LastVisitSnapshot | null,
): DailyBriefSinceLastVisit {
  if (!lastVisit) {
    return {
      hasPriorVisit: false,
      hasChanges: false,
      changes: [],
      summary:
        "Este es el primer briefing ejecutivo que abrimos aquí — desde tu próxima visita, esta sección te dirá exactamente qué cambió.",
    };
  }

  const since = lastVisit.visitedAt;
  const newEvents = workspace.timeline.filter((event) => event.date > since);
  const meetingCount = newEvents.filter((event) => event.category === "meeting").length;
  const knowledgeCount = newEvents.filter((event) => event.category === "knowledge").length;
  const otherCount = newEvents.length - meetingCount - knowledgeCount;
  const understandingDelta =
    Math.round(workspace.businessUnderstanding) - Math.round(lastVisit.businessUnderstanding);

  const changes: DailyBriefChange[] = [];
  if (meetingCount > 0) {
    changes.push({
      id: "meetings",
      label: `${meetingCount} ${pluralEs(meetingCount, "reunión nueva registrada", "reuniones nuevas registradas")}`,
    });
  }
  if (knowledgeCount > 0) {
    changes.push({
      id: "documents",
      label: `${knowledgeCount} ${pluralEs(knowledgeCount, "documento nuevo procesado", "documentos nuevos procesados")}`,
    });
  }
  if (otherCount > 0) {
    changes.push({
      id: "other",
      label: `${otherCount} ${pluralEs(otherCount, "actualización nueva en el diagnóstico", "actualizaciones nuevas en el diagnóstico")}`,
    });
  }
  if (understandingDelta !== 0) {
    changes.push({
      id: "understanding",
      label:
        understandingDelta > 0
          ? `La comprensión del negocio subió de ${clampPercent(lastVisit.businessUnderstanding)}% a ${clampPercent(workspace.businessUnderstanding)}%`
          : `La comprensión del negocio pasó de ${clampPercent(lastVisit.businessUnderstanding)}% a ${clampPercent(workspace.businessUnderstanding)}%`,
    });
  }

  const hasChanges = changes.length > 0;

  return {
    hasPriorVisit: true,
    hasChanges,
    changes,
    summary: hasChanges
      ? `Desde tu última visita: ${changes.map((c) => c.label).join(" · ")}.`
      : "Sin cambios registrados desde tu última visita.",
  };
}

/**
 * "Hoy te recomiendo" — the primary slot is always `NextStepVoice`'s own
 * ranked pick (the senior-consultant judgement call, unchanged). Any
 * remaining slots (up to three total) are the Missing Information Engine's
 * next-highest-impact opportunities that are not already the same topic —
 * never a second ranking model, just the next rows of a list that engine
 * already sorted by estimated business impact.
 */
export function buildRecommendedActions(
  nextStepVoice: NextStepVoice,
  missingInformation: MissingInformationReport,
  discoveryCompletion: DiscoveryCompletionStatus,
): DailyBriefAction[] {
  const actions: DailyBriefAction[] = [
    {
      id: "primary",
      message: nextStepVoice.message,
      actionLabel: nextStepVoice.actionLabel,
      actionKind: nextStepVoice.actionKind,
      focusDimension: nextStepVoice.focusDimension,
      impactLabel: primaryImpactLabel(nextStepVoice, discoveryCompletion),
    },
  ];

  const usedTopics = new Set<string>();
  if (nextStepVoice.focusDimension) usedTopics.add(nextStepVoice.focusDimension);

  for (const opportunity of missingInformation.opportunities) {
    if (actions.length >= MAX_ACTIONS) break;
    if (usedTopics.has(opportunity.topic)) continue;
    usedTopics.add(opportunity.topic);

    const uploadTarget = opportunity.uploadable ? opportunity.uploadSuggestions[0] : undefined;
    actions.push({
      id: opportunity.id,
      message: opportunity.headline,
      actionLabel: uploadTarget
        ? `Subir ${uploadTarget}`
        : `Continuar con ${opportunity.topicLabel}`,
      actionKind: uploadTarget ? "upload_document" : "focus_capability",
      focusDimension: opportunity.topic,
      impactLabel: `+${opportunity.estimatedLiftPercent}%`,
    });
  }

  return actions.slice(0, MAX_ACTIONS);
}

function primaryImpactLabel(
  voice: NextStepVoice,
  discoveryCompletion: DiscoveryCompletionStatus,
): string | null {
  const isInterviewAction =
    voice.actionKind === "focus_capability" || voice.actionKind === "continue_interview";
  if (!isInterviewAction) return null;

  const singleGap =
    discoveryCompletion.missingCapabilities.length === 1
      ? discoveryCompletion.missingCapabilities[0]!
      : null;
  if (singleGap && singleGap.estimatedRemainingMinutes > 0) {
    return `~${singleGap.estimatedRemainingMinutes} min`;
  }
  return null;
}

/**
 * "Próximos hitos" — the same open/untracked capabilities the Discovery
 * Complete ceremony already lists, reduced to the label a glance needs.
 * `discovery-completion-card.tsx` remains the detailed, click-through view
 * of this exact same data — this is the lighter-weight summary for the
 * brief itself.
 */
export function buildMilestones(
  discoveryCompletion: DiscoveryCompletionStatus,
): DailyBriefMilestone[] {
  const open: DailyBriefMilestone[] = discoveryCompletion.missingCapabilities.map((capability) => ({
    id: capability.id,
    label: capability.label,
    state: "open",
    detail: capability.risks[0] ?? null,
  }));
  const notTracked: DailyBriefMilestone[] = discoveryCompletion.notTrackedCapabilities.map(
    (capability) => ({
      id: capability.id,
      label: capability.label,
      state: "not_tracked",
      detail: null,
    }),
  );
  return [...open, ...notTracked];
}

function startOfDay(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate());
}

/**
 * "Aprendizaje reciente" — the same `workspace.timeline` the Assessment tab
 * already renders, grouped into the honest, glanceable Hoy / Ayer / Última
 * semana / Anteriormente buckets the brief asks for. No event is
 * reclassified or reworded — only grouped by real calendar distance from
 * today.
 */
export function groupRecentLearning(workspace: CompanyWorkspace): DailyBriefTimelineGroup[] {
  const sorted = sortTimelineNewestFirst(workspace.timeline).slice(0, MAX_TIMELINE_EVENTS);
  const today = startOfDay(new Date());

  const buckets: Record<DailyBriefTimelineGroup["id"], TimelineEvent[]> = {
    today: [],
    yesterday: [],
    last_week: [],
    earlier: [],
  };

  for (const event of sorted) {
    const diffDays = Math.round(
      (today.getTime() - startOfDay(new Date(event.date)).getTime()) / DAY_MS,
    );
    if (diffDays <= 0) buckets.today.push(event);
    else if (diffDays === 1) buckets.yesterday.push(event);
    else if (diffDays <= 7) buckets.last_week.push(event);
    else buckets.earlier.push(event);
  }

  const labels: Record<DailyBriefTimelineGroup["id"], string> = {
    today: "Hoy",
    yesterday: "Ayer",
    last_week: "Última semana",
    earlier: "Anteriormente",
  };

  return (["today", "yesterday", "last_week", "earlier"] as const)
    .map((id) => ({ id, label: labels[id], events: buckets[id] }))
    .filter((group) => group.events.length > 0);
}

/**
 * Build the full Executive Daily Brief from reports every primary workspace
 * surface already computes once per render (`WorkspaceView`) plus the
 * browser-local last-visit pointer. Pure composition — no recomputation, no
 * new scoring, no fabricated event.
 */
export function buildExecutiveDailyBrief(input: ExecutiveDailyBriefInput): ExecutiveDailyBrief {
  const { workspace, nextStepVoice, missingInformation, discoveryCompletion, lastVisit } = input;
  const understandingPercent = clampPercent(workspace.businessUnderstanding);

  return {
    generatedAt: discoveryCompletion.generatedAt,
    headline: buildHeadline(workspace.companyName, understandingPercent),
    understandingPercent,
    sinceLastVisit: buildSinceLastVisit(workspace, lastVisit),
    actions: buildRecommendedActions(nextStepVoice, missingInformation, discoveryCompletion),
    milestones: buildMilestones(discoveryCompletion),
  };
}
