import type { KnowledgeConnector } from "@/types";

/** Future connector hooks — design only. No OAuth or sync. */
export const KNOWLEDGE_CONNECTORS: readonly KnowledgeConnector[] = [
  {
    id: "google_drive",
    title: "Google Drive",
    description: "Importar carpetas de la empresa al Centro de Conocimiento.",
    status: "planned",
    feedsInto: "knowledge_center",
  },
  {
    id: "dropbox",
    title: "Dropbox",
    description: "Sincronizar documentos compartidos de Dropbox como evidencia.",
    status: "planned",
    feedsInto: "knowledge_center",
  },
  {
    id: "onedrive",
    title: "OneDrive",
    description: "Traer archivos de OneDrive al conocimiento de la empresa.",
    status: "planned",
    feedsInto: "knowledge_center",
  },
  {
    id: "sharepoint",
    title: "SharePoint",
    description: "Ingerir bibliotecas de SharePoint y paquetes de procesos.",
    status: "planned",
    feedsInto: "knowledge_center",
  },
  {
    id: "zoho",
    title: "Zoho",
    description: "Conectores de CRM y documentos para espacios de Zoho.",
    status: "designed",
    feedsInto: "knowledge_center",
  },
  {
    id: "hubspot",
    title: "HubSpot",
    description: "Evidencia de pipeline comercial y contactos.",
    status: "planned",
    feedsInto: "knowledge_center",
  },
  {
    id: "salesforce",
    title: "Salesforce",
    description: "Cuentas, oportunidades e historial de actividad.",
    status: "planned",
    feedsInto: "knowledge_center",
  },
  {
    id: "sap",
    title: "SAP",
    description: "Datos maestros de ERP y exportaciones operativas.",
    status: "planned",
    feedsInto: "knowledge_center",
  },
  {
    id: "quickbooks",
    title: "QuickBooks",
    description: "Facturas, cuentas por cobrar/pagar y estructura financiera.",
    status: "designed",
    feedsInto: "knowledge_center",
  },
  {
    id: "xero",
    title: "Xero",
    description: "Evidencia contable para cobertura financiera.",
    status: "designed",
    feedsInto: "knowledge_center",
  },
  {
    id: "whatsapp",
    title: "WhatsApp",
    description: "Ingesta de exportaciones de chat para procesos informales.",
    status: "designed",
    feedsInto: "knowledge_center",
  },
  {
    id: "google_workspace",
    title: "Google Workspace",
    description: "Artefactos de Docs, Sheets y Meet.",
    status: "planned",
    feedsInto: "knowledge_center",
  },
  {
    id: "microsoft_365",
    title: "Microsoft 365",
    description: "Artefactos de Word, Excel, Outlook y Teams.",
    status: "planned",
    feedsInto: "knowledge_center",
  },
] as const;
