import type {
  CopiedDeliveryLine,
  DeliveryEvidenceRole,
  DeliveryNoteStatus,
  DeliverySubjectType,
  OsDeliveryEventType,
} from '@isalwa/os-contracts';

export type OrderSnapshot = {
  id: string;
  organizationId: string;
  partyId: string;
  orderNumber: string | null;
  status: string;
  lines: readonly unknown[] | null;
};

export type MemberSnapshot = {
  id: string;
  organizationId: string;
  accessStatus: string;
  /** Explicit scopes only. Missing means none. Cargo never fills this. */
  grantedScopes?: readonly string[];
};

export type RecipientCandidate = {
  organizationId: string;
  recipient: string;
};

export type WarehouseExitRecord = {
  id: string;
  organizationId: string;
  orderId: string;
  deliveryNoteId: string | null;
  exitedAt: string;
  recordedByMemberId: string;
  source: 'employee_recorded';
  notes: string | null;
  createdAt: string;
};

export type OutboundNoteRecord = {
  id: string;
  organizationId: string;
  warehouseExitId: string;
  orderId: string;
  documentKind: 'nota_de_salida';
  numberingPolicy: 'unknown';
  noteNumber: null;
  /** Source-preserved printed number. Not generated by OS. */
  externalDocumentNumber: string | null;
  exitedAt: string;
  bornAt: string;
  createdAt: string;
};

export type DeliveryRecord = {
  id: string;
  organizationId: string;
  orderId: string;
  deliveryNoteId: string | null;
  deliveredAt: string;
  deliveredTo: string | null;
  recordedByMemberId: string;
  source: 'employee_recorded';
  notes: string | null;
  createdAt: string;
};

export type DeliveryNoteRecord = {
  id: string;
  organizationId: string;
  deliveryId: string | null;
  orderId: string;
  partyId: string;
  documentKind: 'nota_de_entrega';
  numberingPolicy: 'provisional_internal' | 'unknown';
  noteNumber: null;
  internalDocumentRef: string;
  displayDocumentNumber: string | null;
  /** Source-preserved printed number. Example: 007189. Not generated by OS. */
  externalDocumentNumber: string | null;
  status: DeliveryNoteStatus;
  recipient: string;
  deliveredBy: string;
  receivedBy: string | null;
  observations: string | null;
  locationId: string | null;
  createdByMemberId: string;
  correctsNoteId: string | null;
  supersedesNoteId: string | null;
  correctionReason: string | null;
  deliveredAt: string | null;
  bornAt: string;
  claimsInvoice: false;
  claimsTax: false;
  createdAt: string;
};

export type NoteLineRecord = CopiedDeliveryLine & {
  id: string;
  organizationId: string;
  noteId: string;
};

export type EvidenceRecord = {
  id: string;
  organizationId: string;
  subjectType: DeliverySubjectType;
  subjectId: string;
  role: DeliveryEvidenceRole;
  recordedByMemberId: string;
  reference: string | null;
  note: string | null;
  paymentState: 'reference' | 'authorized_exception' | null;
  exceptionReason: string | null;
  authorizedByMemberId: string | null;
  recipient: string | null;
  signatureReference: string | null;
  confirmedLedgerPayment: false;
  ledgerPosting: 'none';
  signatureMethod: null;
  createdAt: string;
};

export type DeliveryDomainEventRecord = {
  id: string;
  organizationId: string;
  eventType: OsDeliveryEventType;
  partyId: string;
  orderId: string;
  primaryEntityId: string;
  payload: Record<string, unknown>;
  occurredAt: string;
  actorMemberId: string;
};

export type DeliveryIdempotencyRecord = {
  organizationId: string;
  key: string;
  commandName: string;
  resultJson: Record<string, unknown>;
  expiresAt: Date;
};

export interface DeliveryStore {
  getOrderInOrg(organizationId: string, orderId: string): Promise<OrderSnapshot | null>;
  getMemberInOrg(organizationId: string, memberId: string): Promise<MemberSnapshot | null>;
  insertWarehouseExit(row: WarehouseExitRecord): Promise<void>;
  insertOutboundNote(row: OutboundNoteRecord): Promise<void>;
  insertOutboundLines(rows: NoteLineRecord[]): Promise<void>;
  insertDelivery(row: DeliveryRecord): Promise<void>;
  insertDeliveryNote(row: DeliveryNoteRecord): Promise<void>;
  insertDeliveryNoteLines(rows: NoteLineRecord[]): Promise<void>;
  updateDeliveryNote(row: DeliveryNoteRecord): Promise<void>;
  insertEvidence(row: EvidenceRecord): Promise<void>;
  appendDomainEvent(row: DeliveryDomainEventRecord): Promise<void>;
  listWarehouseExits(organizationId: string, orderId: string): Promise<WarehouseExitRecord[]>;
  getOutboundNote(organizationId: string, warehouseExitId: string): Promise<OutboundNoteRecord | null>;
  getWarehouseExit(organizationId: string, warehouseExitId: string): Promise<WarehouseExitRecord | null>;
  listDeliveries(organizationId: string, orderId: string): Promise<DeliveryRecord[]>;
  getDelivery(organizationId: string, deliveryId: string): Promise<DeliveryRecord | null>;
  getDeliveryNote(organizationId: string, deliveryId: string): Promise<DeliveryNoteRecord | null>;
  listDeliveryNotes(organizationId: string, orderId: string): Promise<DeliveryNoteRecord[]>;
  listOutboundLines(organizationId: string, noteId: string): Promise<NoteLineRecord[]>;
  listDeliveryNoteLines(organizationId: string, noteId: string): Promise<NoteLineRecord[]>;
  listEvidence(organizationId: string, subjectType: DeliverySubjectType, subjectId: string): Promise<EvidenceRecord[]>;
  listAllWarehouseExits(organizationId: string): Promise<WarehouseExitRecord[]>;
  listAllDeliveries(organizationId: string): Promise<DeliveryRecord[]>;
  listAllDeliveryNotes(organizationId: string): Promise<DeliveryNoteRecord[]>;
  getDeliveryNoteById(organizationId: string, noteId: string): Promise<DeliveryNoteRecord | null>;
  listRecipientCandidates(organizationId: string): Promise<RecipientCandidate[]>;
  listDomainEvents(organizationId: string, orderId?: string): Promise<DeliveryDomainEventRecord[]>;
  findIdempotency(organizationId: string, key: string): Promise<DeliveryIdempotencyRecord | null>;
  saveIdempotency(record: DeliveryIdempotencyRecord): Promise<void>;
  completeIdempotency(
    organizationId: string,
    key: string,
    resultJson: Record<string, unknown>,
  ): Promise<void>;
  deleteIdempotency(organizationId: string, key: string): Promise<void>;
}
